// Generated by pnpm scrape. Do not edit manually.

import type { WeaponCatalog } from './index';

export const weapons: WeaponCatalog = {
  "Flanker": {
    "Primary": [
      {
        "name": "Baby Face's Blaster",
        "image": "images/weapons/standard/baby-face-s-blaster-c5b4e39017.webp"
      },
      {
        "name": "Colbat",
        "image": "images/weapons/standard/colbat-8d6df9758e.webp"
      },
      {
        "name": "Lever Shotgun",
        "image": "images/weapons/standard/lever-shotgun-7fb5a25428.webp",
        "stock": true
      },
      {
        "name": "Lupara DB",
        "image": "images/weapons/standard/lupara-db-40d6b259a6.webp"
      },
      {
        "name": "Mach-Coach",
        "image": "images/weapons/standard/mach-coach-9b9bf85581.webp"
      },
      {
        "name": "Mule Mauler 600",
        "image": "images/weapons/standard/mule-mauler-600-adee161e26.webp"
      },
      {
        "name": "Perceptionist",
        "image": "images/weapons/standard/perceptionist-7f0b7666fb.webp"
      },
      {
        "name": "Shotgun Cannon",
        "image": "images/weapons/standard/shotgun-cannon-fcafbdb2b7.webp"
      },
      {
        "name": "Soda Popper",
        "image": "images/weapons/standard/soda-popper-45ac0fbe12.webp"
      },
      {
        "name": "Specialist",
        "image": "images/weapons/standard/specialist-84873986db.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Batarang",
        "image": "images/weapons/standard/batarang-5c2315f981.webp"
      },
      {
        "name": "Bloxaide",
        "image": "images/weapons/standard/bloxaide-0fa23a490a.webp"
      },
      {
        "name": "Bloxy Cola",
        "image": "images/weapons/standard/bloxy-cola-27cc9ad45b.webp"
      },
      {
        "name": "Concealed Carry",
        "image": "images/weapons/standard/concealed-carry-8641e84234.webp"
      },
      {
        "name": "Conventional",
        "image": "images/weapons/standard/conventional-19a64068e8.webp"
      },
      {
        "name": "Goala Cola",
        "image": "images/weapons/standard/goala-cola-00d15f2202.webp"
      },
      {
        "name": "Hot Coco Blast",
        "image": "images/weapons/standard/hot-coco-blast-893e96ee75.webp"
      },
      {
        "name": "Mad Milk",
        "image": "images/weapons/standard/mad-milk-e2574af1a1.webp"
      },
      {
        "name": "Pistol",
        "image": "images/weapons/standard/pistol-6519b54c34.webp",
        "stock": true
      },
      {
        "name": "Raven",
        "image": "images/weapons/standard/raven-00eabc4db6.webp"
      },
      {
        "name": "Super Sneakers",
        "image": "images/weapons/standard/super-sneakers-3e5b079f4d.webp"
      },
      {
        "name": "Winger",
        "image": "images/weapons/standard/winger-100b3a9c85.webp"
      },
      {
        "name": "Witches Brew",
        "image": "images/weapons/standard/witches-brew-74470cedda.webp"
      }
    ],
    "Melee": [
      {
        "name": "Atomizer",
        "image": "images/weapons/standard/atomizer-ac3d17ec70.webp"
      },
      {
        "name": "Bat",
        "image": "images/weapons/standard/bat-0cbe053a63.webp",
        "stock": true
      },
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Brooklyn Basher",
        "image": "images/weapons/standard/brooklyn-basher-9fac3de845.webp"
      },
      {
        "name": "Candy Cane",
        "image": "images/weapons/standard/candy-cane-8387882564.webp"
      },
      {
        "name": "Frying Pan",
        "image": "images/weapons/standard/frying-pan-1ea55bf6c0.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Grill Scout",
        "image": "images/weapons/standard/grill-scout-df3ee917bf.webp"
      },
      {
        "name": "Handyman",
        "image": "images/weapons/standard/handyman-c15e631708.webp"
      },
      {
        "name": "Holy Mackerel",
        "image": "images/weapons/standard/holy-mackerel-0b2c4030cc.webp"
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "Objector",
        "image": "images/weapons/standard/objector-90e9274d74.webp"
      },
      {
        "name": "Rubber Chicken",
        "image": "images/weapons/standard/rubber-chicken-ff5b060b18.webp"
      },
      {
        "name": "Three Rune Blade",
        "image": "images/weapons/standard/three-rune-blade-de64b0c462.webp"
      },
      {
        "name": "Wooden Sword",
        "image": "images/weapons/standard/wooden-sword-74a72c948d.webp"
      }
    ]
  },
  "Trooper": {
    "Primary": [
      {
        "name": "Big Bite",
        "image": "images/weapons/standard/big-bite-26f84ddb92.webp"
      },
      {
        "name": "Direct Hit",
        "image": "images/weapons/standard/direct-hit-7b2a597b9b.webp"
      },
      {
        "name": "Double Trouble",
        "image": "images/weapons/standard/double-trouble-24b50a7c9f.webp"
      },
      {
        "name": "Friendly Fire Foiler",
        "image": "images/weapons/standard/friendly-fire-foiler-e3051b58d4.webp"
      },
      {
        "name": "G-Bomb",
        "image": "images/weapons/standard/g-bomb-f14403726b.webp"
      },
      {
        "name": "Great Unifier",
        "image": "images/weapons/standard/great-unifier-2cfddc05d9.webp"
      },
      {
        "name": "Liberty Launcher",
        "image": "images/weapons/standard/liberty-launcher-f2397d6d9c.webp"
      },
      {
        "name": "Maverick",
        "image": "images/weapons/standard/maverick-ce6c58f563.webp"
      },
      {
        "name": "Night Sky Ignitor",
        "image": "images/weapons/standard/night-sky-ignitor-53af9dc38d.webp"
      },
      {
        "name": "Original",
        "image": "images/weapons/standard/original-952a4deeee.webp"
      },
      {
        "name": "RE:COIL",
        "image": "images/weapons/standard/re-coil-db4e28f6eb.webp"
      },
      {
        "name": "Rocket Jumper",
        "image": "images/weapons/standard/rocket-jumper-2832b7d0d2.webp"
      },
      {
        "name": "Rocket Launcher",
        "image": "images/weapons/standard/rocket-launcher-9c4107cd9c.webp",
        "stock": true
      },
      {
        "name": "Stellar Carpet",
        "image": "images/weapons/standard/stellar-carpet-6709c82257.webp"
      },
      {
        "name": "Wrecker's Yard",
        "image": "images/weapons/standard/wrecker-s-yard-676a1ba8a6.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Armington",
        "image": "images/weapons/standard/armington-f97cba7272.webp"
      },
      {
        "name": "Battalion's Backup",
        "image": "images/weapons/standard/battalion-s-backup-dd2def1293.webp"
      },
      {
        "name": "Boonie Blaster",
        "image": "images/weapons/standard/boonie-blaster-80787f81cd.webp"
      },
      {
        "name": "Buff Banner",
        "image": "images/weapons/standard/buff-banner-de9833ce9e.webp"
      },
      {
        "name": "Buffin' Blitz",
        "image": "images/weapons/standard/buffin-blitz-266b5dbf84.webp"
      },
      {
        "name": "Bullet-stormer",
        "image": "images/weapons/standard/bullet-stormer-8389c4e0f0.webp"
      },
      {
        "name": "Concheror",
        "image": "images/weapons/standard/concheror-ef2586018e.webp"
      },
      {
        "name": "Crankenstein",
        "image": "images/weapons/standard/crankenstein-bd69bb5573.webp"
      },
      {
        "name": "Deathblow",
        "image": "images/weapons/standard/deathblow-d10ecafbc7.webp"
      },
      {
        "name": "Eyes of Bermuda",
        "image": "images/weapons/standard/eyes-of-bermuda-d641525baa.webp"
      },
      {
        "name": "Family Business",
        "image": "images/weapons/standard/family-business-e46e6b37f5.webp"
      },
      {
        "name": "Gunboats",
        "image": "images/weapons/standard/gunboats-b69e186ffe.webp"
      },
      {
        "name": "Mantreads",
        "image": "images/weapons/standard/mantreads-a93e4225bc.webp"
      },
      {
        "name": "Parabomber",
        "image": "images/weapons/standard/parabomber-759ff81bf3.webp"
      },
      {
        "name": "Personal Death Ray",
        "image": "images/weapons/standard/personal-death-ray-36f4801233.webp"
      },
      {
        "name": "Reserve Shooter",
        "image": "images/weapons/standard/reserve-shooter-90c3e34856.webp"
      },
      {
        "name": "Shotgun",
        "image": "images/weapons/standard/shotgun-afde9473cd.webp",
        "stock": true
      }
    ],
    "Melee": [
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Crowbar",
        "image": "images/weapons/standard/crowbar-a99fbfbb34.webp",
        "stock": true
      },
      {
        "name": "Equalizer",
        "image": "images/weapons/standard/equalizer-fa43020b6b.webp"
      },
      {
        "name": "Escape Plan",
        "image": "images/weapons/standard/escape-plan-ec0ceeb876.webp"
      },
      {
        "name": "Frying Pan",
        "image": "images/weapons/standard/frying-pan-1ea55bf6c0.webp"
      },
      {
        "name": "Furious Flagxe",
        "image": "images/weapons/standard/furious-flagxe-042d85c785.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Katana",
        "image": "images/weapons/standard/katana-ce63ad79ff.webp"
      },
      {
        "name": "Market Gardener",
        "image": "images/weapons/standard/market-gardener-1b00cf6f30.webp"
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "Mummy Khopesh",
        "image": "images/weapons/standard/mummy-khopesh-d8d5c8aea9.webp"
      },
      {
        "name": "Objector",
        "image": "images/weapons/standard/objector-90e9274d74.webp"
      },
      {
        "name": "Rising Sun Katana",
        "image": "images/weapons/standard/rising-sun-katana-228e0a903d.webp"
      },
      {
        "name": "SlapJock!",
        "image": "images/weapons/standard/slapjock-36fb0ce537.webp"
      },
      {
        "name": "Tunnel Rat",
        "image": "images/weapons/standard/tunnel-rat-60b2293821.webp"
      }
    ]
  },
  "Arsonist": {
    "Primary": [
      {
        "name": "Degreaser",
        "image": "images/weapons/standard/degreaser-4019efe531.webp"
      },
      {
        "name": "Flamethrower",
        "image": "images/weapons/standard/flamethrower-b7d448a8d5.webp",
        "stock": true
      },
      {
        "name": "HuangLong's Wrath",
        "image": "images/weapons/standard/huanglong-s-wrath-b9fa070309.webp"
      },
      {
        "name": "Interceptor",
        "image": "images/weapons/standard/interceptor-5fc9a25361.webp"
      },
      {
        "name": "Phlogistinator",
        "image": "images/weapons/standard/phlogistinator-be34d9a413.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Armington",
        "image": "images/weapons/standard/armington-f97cba7272.webp"
      },
      {
        "name": "Bullet-stormer",
        "image": "images/weapons/standard/bullet-stormer-8389c4e0f0.webp"
      },
      {
        "name": "Crankenstein",
        "image": "images/weapons/standard/crankenstein-bd69bb5573.webp"
      },
      {
        "name": "Deathblow",
        "image": "images/weapons/standard/deathblow-d10ecafbc7.webp"
      },
      {
        "name": "Detonator",
        "image": "images/weapons/standard/detonator-52b3ca082e.webp"
      },
      {
        "name": "Eyes of Bermuda",
        "image": "images/weapons/standard/eyes-of-bermuda-d641525baa.webp"
      },
      {
        "name": "Family Business",
        "image": "images/weapons/standard/family-business-e46e6b37f5.webp"
      },
      {
        "name": "Flare Gun",
        "image": "images/weapons/standard/flare-gun-e721453ff0.webp"
      },
      {
        "name": "Shotgun",
        "image": "images/weapons/standard/shotgun-afde9473cd.webp",
        "stock": true
      }
    ],
    "Melee": [
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Escapist's Escapade",
        "image": "images/weapons/standard/escapist-s-escapade-87282a82b0.webp"
      },
      {
        "name": "Fire Extinguisher",
        "image": "images/weapons/standard/fire-extinguisher-e049bb59ac.webp",
        "stock": true
      },
      {
        "name": "Frying Pan",
        "image": "images/weapons/standard/frying-pan-1ea55bf6c0.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Hotwire",
        "image": "images/weapons/standard/hotwire-13473047a8.webp"
      },
      {
        "name": "Improvised Innovator",
        "image": "images/weapons/standard/improvised-innovator-5e55472034.webp"
      },
      {
        "name": "Last Rite",
        "image": "images/weapons/standard/last-rite-9bb92d8422.webp"
      },
      {
        "name": "Mending Mallet",
        "image": "images/weapons/standard/mending-mallet-88cb4e1b66.webp"
      },
      {
        "name": "Mummy Khopesh",
        "image": "images/weapons/standard/mummy-khopesh-d8d5c8aea9.webp"
      },
      {
        "name": "Objector",
        "image": "images/weapons/standard/objector-90e9274d74.webp"
      },
      {
        "name": "Thousand Degree Axe",
        "image": "images/weapons/standard/thousand-degree-axe-7e02f36776.webp"
      }
    ]
  },
  "Annihilator": {
    "Primary": [
      {
        "name": "Acid Trader",
        "image": "images/weapons/standard/acid-trader-b4d8506e9f.webp"
      },
      {
        "name": "BlunderBrass",
        "image": "images/weapons/standard/blunderbrass-8b69247a0e.webp"
      },
      {
        "name": "Galway Greaves",
        "image": "images/weapons/standard/galway-greaves-a0c5ec275b.webp"
      },
      {
        "name": "Grenade Launcher",
        "image": "images/weapons/standard/grenade-launcher-beb7ae4362.webp",
        "stock": true
      },
      {
        "name": "Gunboats",
        "image": "images/weapons/standard/gunboats-b69e186ffe.webp"
      },
      {
        "name": "Iron Force",
        "image": "images/weapons/standard/iron-force-8e99054317.webp"
      },
      {
        "name": "Jack-O Roger",
        "image": "images/weapons/standard/jack-o-roger-202ffef8b8.webp"
      },
      {
        "name": "M1 Garandier",
        "image": "images/weapons/standard/m1-garandier-3f2b7b9e95.webp"
      },
      {
        "name": "Parabomber",
        "image": "images/weapons/standard/parabomber-759ff81bf3.webp"
      },
      {
        "name": "Squire Boots",
        "image": "images/weapons/standard/squire-boots-4d881d3d80.webp"
      },
      {
        "name": "Twin-Turbolence",
        "image": "images/weapons/standard/twin-turbolence-6bf3a09afc.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Bloody Blossom",
        "image": "images/weapons/standard/bloody-blossom-8419a38ab7.webp"
      },
      {
        "name": "Chargin' Targe",
        "image": "images/weapons/standard/chargin-targe-9f0d192895.webp"
      },
      {
        "name": "Gladiator's Guard",
        "image": "images/weapons/standard/gladiator-s-guard-e99d5b7ed2.webp"
      },
      {
        "name": "Irish Guard",
        "image": "images/weapons/standard/irish-guard-33df295fcf.webp"
      },
      {
        "name": "Quickiebomb Launcher",
        "image": "images/weapons/standard/quickiebomb-launcher-67691232cf.webp"
      },
      {
        "name": "Ragin' Bull",
        "image": "images/weapons/standard/ragin-bull-94550f1c89.webp"
      },
      {
        "name": "Sticky Jumper",
        "image": "images/weapons/standard/sticky-jumper-a68be1e6fb.webp"
      },
      {
        "name": "Stickybomb Launcher",
        "image": "images/weapons/standard/stickybomb-launcher-90e2a22e9b.webp",
        "stock": true
      },
      {
        "name": "Tide Turner",
        "image": "images/weapons/standard/tide-turner-9ab515c31d.webp"
      }
    ],
    "Melee": [
      {
        "name": "Battle Axe",
        "image": "images/weapons/standard/battle-axe-5620da4548.webp"
      },
      {
        "name": "Black Death",
        "image": "images/weapons/standard/black-death-9d969a5276.webp"
      },
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Broken Sword",
        "image": "images/weapons/standard/broken-sword-762c66e15b.webp",
        "stock": true
      },
      {
        "name": "Cuteness Overload",
        "image": "images/weapons/standard/cuteness-overload-7215ae2a10.webp"
      },
      {
        "name": "Darkness",
        "image": "images/weapons/standard/darkness-2df0ef3e37.webp"
      },
      {
        "name": "Elegant Blade",
        "image": "images/weapons/standard/elegant-blade-785cf90d21.webp"
      },
      {
        "name": "Frying Pan",
        "image": "images/weapons/standard/frying-pan-1ea55bf6c0.webp"
      },
      {
        "name": "Furious Flagxe",
        "image": "images/weapons/standard/furious-flagxe-042d85c785.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Golf Club",
        "image": "images/weapons/standard/golf-club-3d8e73c546.webp"
      },
      {
        "name": "Katana",
        "image": "images/weapons/standard/katana-ce63ad79ff.webp"
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "Mummy Khopesh",
        "image": "images/weapons/standard/mummy-khopesh-d8d5c8aea9.webp"
      },
      {
        "name": "Objector",
        "image": "images/weapons/standard/objector-90e9274d74.webp"
      },
      {
        "name": "Pirate Cutlass",
        "image": "images/weapons/standard/pirate-cutlass-15f3de203f.webp"
      },
      {
        "name": "Rising Sun Katana",
        "image": "images/weapons/standard/rising-sun-katana-228e0a903d.webp"
      },
      {
        "name": "Shock and Awe",
        "image": "images/weapons/standard/shock-and-awe-be7c16fa85.webp"
      },
      {
        "name": "Spartan Savior",
        "image": "images/weapons/standard/spartan-savior-767913bcc9.webp"
      },
      {
        "name": "Whirlpool Wraith",
        "image": "images/weapons/standard/whirlpool-wraith-f1ef52f79b.webp"
      }
    ]
  },
  "Brute": {
    "Primary": [
      {
        "name": "Biker's Blitz",
        "image": "images/weapons/standard/biker-s-blitz-65952504d8.webp"
      },
      {
        "name": "First Responder",
        "image": "images/weapons/standard/first-responder-ea0814d7ef.webp"
      },
      {
        "name": "Groovy Grinder",
        "image": "images/weapons/standard/groovy-grinder-f9142a68c9.webp"
      },
      {
        "name": "M249",
        "image": "images/weapons/standard/m249-aaff6ea00b.webp"
      },
      {
        "name": "Maxine",
        "image": "images/weapons/standard/maxine-beaece3bbd.webp"
      },
      {
        "name": "Minigun",
        "image": "images/weapons/standard/minigun-d5b1f166e1.webp",
        "stock": true
      },
      {
        "name": "Monitor of Duty",
        "image": "images/weapons/standard/monitor-of-duty-e6a26f5011.webp"
      },
      {
        "name": "Tomislav",
        "image": "images/weapons/standard/tomislav-898567aacf.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Armington",
        "image": "images/weapons/standard/armington-f97cba7272.webp"
      },
      {
        "name": "Battle Burrito",
        "image": "images/weapons/standard/battle-burrito-81d2210356.webp"
      },
      {
        "name": "Brash Burger",
        "image": "images/weapons/standard/brash-burger-73efbc9bae.webp"
      },
      {
        "name": "Bullet-stormer",
        "image": "images/weapons/standard/bullet-stormer-8389c4e0f0.webp"
      },
      {
        "name": "Crankenstein",
        "image": "images/weapons/standard/crankenstein-bd69bb5573.webp"
      },
      {
        "name": "Deathblow",
        "image": "images/weapons/standard/deathblow-d10ecafbc7.webp"
      },
      {
        "name": "Diggity Dog",
        "image": "images/weapons/standard/diggity-dog-5a3e655f8d.webp"
      },
      {
        "name": "Dire Donut",
        "image": "images/weapons/standard/dire-donut-0af9567a60.webp"
      },
      {
        "name": "Eyes of Bermuda",
        "image": "images/weapons/standard/eyes-of-bermuda-d641525baa.webp"
      },
      {
        "name": "Family Business",
        "image": "images/weapons/standard/family-business-e46e6b37f5.webp"
      },
      {
        "name": "Jolly Gingerbread",
        "image": "images/weapons/standard/jolly-gingerbread-c351a2000e.webp"
      },
      {
        "name": "ROBAR",
        "image": "images/weapons/standard/robar-a86b8c7faf.webp"
      },
      {
        "name": "Second Banana",
        "image": "images/weapons/standard/second-banana-66f295fcc9.webp"
      },
      {
        "name": "Shotgun",
        "image": "images/weapons/standard/shotgun-afde9473cd.webp",
        "stock": true
      },
      {
        "name": "Special-Ops Sushi",
        "image": "images/weapons/standard/special-ops-sushi-95a41625d8.webp"
      },
      {
        "name": "Sub Shotgun",
        "image": "images/weapons/standard/sub-shotgun-669021a8be.webp"
      },
      {
        "name": "Tenacious Turkey",
        "image": "images/weapons/standard/tenacious-turkey-8306997ebb.webp"
      },
      {
        "name": "Tungsten Torus",
        "image": "images/weapons/standard/tungsten-torus-725aed75f3.webp"
      }
    ],
    "Melee": [
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Boxing Gloves",
        "image": "images/weapons/standard/boxing-gloves-96999051cb.webp"
      },
      {
        "name": "Eviction Notice",
        "image": "images/weapons/standard/eviction-notice-6f04fb226e.webp"
      },
      {
        "name": "Fists",
        "image": "images/weapons/standard/fists-d1ecc56e14.webp",
        "stock": true
      },
      {
        "name": "Fists of Steel",
        "image": "images/weapons/standard/fists-of-steel-e7af3d8ab0.webp"
      },
      {
        "name": "Frying Pan",
        "image": "images/weapons/standard/frying-pan-1ea55bf6c0.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Gravity Coil",
        "image": "images/weapons/standard/gravity-coil-1d0f92883e.webp"
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "Objector",
        "image": "images/weapons/standard/objector-90e9274d74.webp"
      },
      {
        "name": "Speed Coil",
        "image": "images/weapons/standard/speed-coil-45542b3fdc.webp"
      },
      {
        "name": "Squid Coil",
        "image": "images/weapons/standard/squid-coil-21d396113f.webp"
      },
      {
        "name": "Warrior's Spirit",
        "image": "images/weapons/standard/warrior-s-spirit-7bf3c28e37.webp"
      }
    ]
  },
  "Mechanic": {
    "Primary": [
      {
        "name": "Armington",
        "image": "images/weapons/standard/armington-f97cba7272.webp"
      },
      {
        "name": "Avengeance",
        "image": "images/weapons/standard/avengeance-09a589a06a.webp"
      },
      {
        "name": "Bullet-stormer",
        "image": "images/weapons/standard/bullet-stormer-8389c4e0f0.webp"
      },
      {
        "name": "Crankenstein",
        "image": "images/weapons/standard/crankenstein-bd69bb5573.webp"
      },
      {
        "name": "Einsteinium",
        "image": "images/weapons/standard/einsteinium-efc47ab04e.webp"
      },
      {
        "name": "Eyes of Bermuda",
        "image": "images/weapons/standard/eyes-of-bermuda-d641525baa.webp"
      },
      {
        "name": "Family Business",
        "image": "images/weapons/standard/family-business-e46e6b37f5.webp"
      },
      {
        "name": "Gutbuster",
        "image": "images/weapons/standard/gutbuster-27553a58dd.webp"
      },
      {
        "name": "Rescue Ranger",
        "image": "images/weapons/standard/rescue-ranger-4cb26a420a.webp"
      },
      {
        "name": "Shotgun",
        "image": "images/weapons/standard/shotgun-afde9473cd.webp",
        "stock": true
      },
      {
        "name": "Widowmaker",
        "image": "images/weapons/standard/widowmaker-34ec3f0ba8.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Conventional",
        "image": "images/weapons/standard/conventional-19a64068e8.webp"
      },
      {
        "name": "Heavy Metal",
        "image": "images/weapons/standard/heavy-metal-bfea354bfb.webp"
      },
      {
        "name": "Noisy Cricket",
        "image": "images/weapons/standard/noisy-cricket-ff3534da22.webp"
      },
      {
        "name": "Pistol",
        "image": "images/weapons/standard/pistol-6519b54c34.webp",
        "stock": true
      },
      {
        "name": "Short Circuit",
        "image": "images/weapons/standard/short-circuit-61ce3bc5b0.webp"
      },
      {
        "name": "Wrangler",
        "image": "images/weapons/standard/wrangler-1e97a85e58.webp"
      }
    ],
    "Melee": [
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Doll Maker",
        "image": "images/weapons/standard/doll-maker-e375e43a9b.webp"
      },
      {
        "name": "Eureka Effect",
        "image": "images/weapons/standard/eureka-effect-5a3801e169.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Golden Wrench",
        "image": "images/weapons/standard/golden-wrench-fde6874076.webp"
      },
      {
        "name": "Gunslinger",
        "image": "images/weapons/standard/gunslinger-465778034a.webp"
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "P.D.Q",
        "image": "images/weapons/standard/p-d-q-6f0665d3b1.webp"
      },
      {
        "name": "Southern Hospitality",
        "image": "images/weapons/standard/southern-hospitality-f53f3b7c7f.webp"
      },
      {
        "name": "Wrench",
        "image": "images/weapons/standard/wrench-02f3a7592e.webp",
        "stock": true
      }
    ]
  },
  "Doctor": {
    "Primary": [
      {
        "name": "Apollo",
        "image": "images/weapons/standard/apollo-edf83cc628.webp"
      },
      {
        "name": "Dairy Douser",
        "image": "images/weapons/standard/dairy-douser-336b81f896.webp"
      },
      {
        "name": "Mercy Kill",
        "image": "images/weapons/standard/mercy-kill-443ff9cde4.webp"
      },
      {
        "name": "Overdrive",
        "image": "images/weapons/standard/overdrive-7f584b5cb0.webp"
      },
      {
        "name": "Syringe Crossbow",
        "image": "images/weapons/standard/syringe-crossbow-da307c696a.webp",
        "stock": true
      },
      {
        "name": "Syringe SMG",
        "image": "images/weapons/standard/syringe-smg-5b1970c72f.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Blood Doctor",
        "image": "images/weapons/standard/blood-doctor-5a6f64c216.webp"
      },
      {
        "name": "Kritzkrieg",
        "image": "images/weapons/standard/kritzkrieg-6a6d6c427f.webp"
      },
      {
        "name": "Malpractitioner",
        "image": "images/weapons/standard/malpractitioner-0b1e1d7f44.webp"
      },
      {
        "name": "Medigun",
        "image": "images/weapons/standard/medigun-dd0c825c0d.webp",
        "stock": true
      },
      {
        "name": "Rejuvenator",
        "image": "images/weapons/standard/rejuvenator-bdad56896b.webp"
      },
      {
        "name": "Vaccinator",
        "image": "images/weapons/standard/vaccinator-128ade393b.webp"
      }
    ],
    "Melee": [
      {
        "name": "Amputator",
        "image": "images/weapons/standard/amputator-e5b65abd9b.webp"
      },
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Dentist's Delight",
        "image": "images/weapons/standard/dentist-s-delight-716407b39a.webp"
      },
      {
        "name": "Frying Pan",
        "image": "images/weapons/standard/frying-pan-1ea55bf6c0.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "Objector",
        "image": "images/weapons/standard/objector-90e9274d74.webp"
      },
      {
        "name": "Pestilence Poker",
        "image": "images/weapons/standard/pestilence-poker-c41daa44d4.webp"
      },
      {
        "name": "Saw",
        "image": "images/weapons/standard/saw-7cdc0205a7.webp",
        "stock": true
      },
      {
        "name": "Supersaw",
        "image": "images/weapons/standard/supersaw-fb8325c164.webp"
      }
    ]
  },
  "Marksman": {
    "Primary": [
      {
        "name": "AWSM-SCE",
        "image": "images/weapons/standard/awsm-sce-9933645e4a.webp"
      },
      {
        "name": "Classic",
        "image": "images/weapons/standard/classic-447b653057.webp"
      },
      {
        "name": "Efficient Eliminator",
        "image": "images/weapons/standard/efficient-eliminator-8357b08918.webp"
      },
      {
        "name": "Huntsman",
        "image": "images/weapons/standard/huntsman-e44d406a0b.webp"
      },
      {
        "name": "Model IV",
        "image": "images/weapons/standard/model-iv-f6a61b7319.webp"
      },
      {
        "name": "Poacher's Pride",
        "image": "images/weapons/standard/poacher-s-pride-ea4e36515f.webp"
      },
      {
        "name": "Scythe for Sore Eyes",
        "image": "images/weapons/standard/scythe-for-sore-eyes-a26d837f9e.webp"
      },
      {
        "name": "Skullbuster",
        "image": "images/weapons/standard/skullbuster-a0e3c26aaa.webp"
      },
      {
        "name": "Sniper Rifle",
        "image": "images/weapons/standard/sniper-rifle-64112c64ee.webp",
        "stock": true
      },
      {
        "name": "Sour Shots",
        "image": "images/weapons/standard/sour-shots-381022cca3.webp"
      },
      {
        "name": "Spider Bite",
        "image": "images/weapons/standard/spider-bite-fa6be039c7.webp"
      },
      {
        "name": "Urban Upriser",
        "image": "images/weapons/standard/urban-upriser-f063f4e4f1.webp"
      }
    ],
    "Secondary": [
      {
        "name": "50-AE",
        "image": "images/weapons/standard/50-ae-eb9dc7e05c.webp"
      },
      {
        "name": "Bottled Lemonade",
        "image": "images/weapons/standard/bottled-lemonade-8737a4a662.webp"
      },
      {
        "name": "Citric Reaction",
        "image": "images/weapons/standard/citric-reaction-072bc1df57.webp"
      },
      {
        "name": "Counter-Service",
        "image": "images/weapons/standard/counter-service-0cf4f561dc.webp"
      },
      {
        "name": "Hermits' Haversack",
        "image": "images/weapons/standard/hermits-haversack-42fa5041ac.webp"
      },
      {
        "name": "Lemonade",
        "image": "images/weapons/standard/lemonade-3d97d6919b.webp"
      },
      {
        "name": "MAC-10",
        "image": "images/weapons/standard/mac-10-cb66c33b3b.webp",
        "stock": true
      },
      {
        "name": "Razorback",
        "image": "images/weapons/standard/razorback-25f062614b.webp"
      },
      {
        "name": "Suppressed Solution",
        "image": "images/weapons/standard/suppressed-solution-aec700e916.webp"
      },
      {
        "name": "Turtle Rock",
        "image": "images/weapons/standard/turtle-rock-04d6ce2d07.webp"
      }
    ],
    "Melee": [
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Camper's Climber",
        "image": "images/weapons/standard/camper-s-climber-72f10bb27d.webp"
      },
      {
        "name": "Frying Pan",
        "image": "images/weapons/standard/frying-pan-1ea55bf6c0.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Guardian's Oath",
        "image": "images/weapons/standard/guardian-s-oath-50c31a7f98.webp"
      },
      {
        "name": "Gustabe",
        "image": "images/weapons/standard/gustabe-16bddae0df.webp"
      },
      {
        "name": "Lemoblade",
        "image": "images/weapons/standard/lemoblade-ac2691fc4a.webp"
      },
      {
        "name": "Machete",
        "image": "images/weapons/standard/machete-53813b8d23.webp",
        "stock": true
      },
      {
        "name": "Mischievous Machete",
        "image": "images/weapons/standard/mischievous-machete-b05296d34b.webp"
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "Mummy Khopesh",
        "image": "images/weapons/standard/mummy-khopesh-d8d5c8aea9.webp"
      },
      {
        "name": "Objector",
        "image": "images/weapons/standard/objector-90e9274d74.webp"
      }
    ]
  },
  "Agent": {
    "Primary": [
      {
        "name": "Block-17",
        "image": "images/weapons/standard/block-17-4db78bbea5.webp"
      },
      {
        "name": "Cloak Revolver",
        "image": "images/weapons/standard/cloak-revolver-cb18e53252.webp"
      },
      {
        "name": "Diavolo",
        "image": "images/weapons/standard/diavolo-44eb564660.webp"
      },
      {
        "name": "Quick Draw",
        "image": "images/weapons/standard/quick-draw-39900e754c.webp"
      },
      {
        "name": "Revolver",
        "image": "images/weapons/standard/revolver-b6cc60f888.webp",
        "stock": true
      },
      {
        "name": "Silenced Pistol",
        "image": "images/weapons/standard/silenced-pistol-523d932967.webp"
      }
    ],
    "Secondary": [
      {
        "name": "Cloak and Dagger",
        "image": "images/weapons/standard/cloak-and-dagger-f76b7faacc.webp"
      },
      {
        "name": "Dead Ringer",
        "image": "images/weapons/standard/dead-ringer-5548211e76.webp"
      },
      {
        "name": "Invis-Watch",
        "image": "images/weapons/standard/invis-watch-3de976cce9.webp",
        "stock": true
      }
    ],
    "Melee": [
      {
        "name": "Bloxy Award",
        "image": "images/weapons/standard/bloxy-award-e0d3963b19.webp"
      },
      {
        "name": "Conniver's Kunai",
        "image": "images/weapons/standard/conniver-s-kunai-aac0359911.webp"
      },
      {
        "name": "Golden Frying Pan",
        "image": "images/weapons/standard/golden-frying-pan-d7cf3366ee.webp"
      },
      {
        "name": "Golden Knife",
        "image": "images/weapons/standard/golden-knife-85e4dcd7d8.webp"
      },
      {
        "name": "Grin Reaper",
        "image": "images/weapons/standard/grin-reaper-af1371981e.webp"
      },
      {
        "name": "Icicle",
        "image": "images/weapons/standard/icicle-d3664857f2.webp"
      },
      {
        "name": "Knife",
        "image": "images/weapons/standard/knife-b95bb2dc34.webp",
        "stock": true
      },
      {
        "name": "Mod Max",
        "image": "images/weapons/standard/mod-max-a1b9c972fe.webp"
      },
      {
        "name": "Shadow Blessing",
        "image": "images/weapons/standard/shadow-blessing-dc53aa84d2.webp"
      },
      {
        "name": "Swift Stiletto",
        "image": "images/weapons/standard/swift-stiletto-e8ae8e7647.webp"
      },
      {
        "name": "Your Eternal Reward",
        "image": "images/weapons/standard/your-eternal-reward-4c461e74bb.webp"
      }
    ],
    "PDA": [
      {
        "name": "Radius Scanner",
        "image": "images/weapons/standard/radius-scanner-7b6f92c3a3.webp"
      },
      {
        "name": "Sapper",
        "image": "images/weapons/standard/sapper-915516a4d9.webp",
        "stock": true
      },
      {
        "name": "Slow Burn",
        "image": "images/weapons/standard/slow-burn-fa6f4d9144.webp"
      },
      {
        "name": "Spy Camera",
        "image": "images/weapons/standard/spy-camera-d8a6ec8e89.webp"
      },
      {
        "name": "Stray Reflex",
        "image": "images/weapons/standard/stray-reflex-08c27aebad.webp"
      }
    ]
  }
};
