import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { PartialWeaponCatalog } from '../../src/data';
import { clean, imageUrl, downloadImage } from './images';
import { classes, slots, fetchPage, experimentalTable, type ClassName, type Slot } from './wiki';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const assetDirectory = path.join(projectRoot, 'public/images/weapons/experimental');
const outputFile = path.join(projectRoot, 'src/data/experimental.generated.ts');
type Item = { className: ClassName; name: string; imageUrl: string; page: string };
type SlottedItem = Item & { slot: Slot };
type LocalItem = SlottedItem & { image: string };

function readItem(cell: Element, className: ClassName): Item | null {
  const name = clean(cell.textContent ?? '');
  const links = [...cell.querySelectorAll("a[href*='/wiki/']")];
  const weaponLink = links.findLast(
    (link) => clean(link.textContent || link.getAttribute('title') || '') === name,
  );
  const remoteImage = imageUrl(cell.querySelector('img'));
  const page = weaponLink?.getAttribute('title') || name;
  if (!name || !page || !remoteImage) return null;
  return { className, name, imageUrl: remoteImage, page };
}

function parseItems(document: Document): Item[] {
  const items = new Map<string, Item>();
  let currentClass: ClassName | undefined;
  for (const row of experimentalTable(document).querySelectorAll('tr')) {
    for (const cell of row.children) {
      const text = clean(cell.textContent ?? '');
      const className = classes.find((name) => text === name);
      if (className) {
        currentClass = className;
        continue;
      }
      if (!currentClass || cell.tagName !== 'TD') continue;
      const item = readItem(cell, currentClass);
      if (item) items.set(`${item.className}\0${item.name}`, item);
    }
  }
  return [...items.values()];
}

function slotFromCategories(categories: string[]): Slot | undefined {
  const normalized = categories.map((category) => category.replace(/_/g, ' ').toLowerCase());
  return slots.find((slot) =>
    normalized.some((category) => category.includes(`${slot.toLowerCase()} weapons`)),
  );
}

async function addSlots(items: Item[]): Promise<SlottedItem[]> {
  return Promise.all(
    items.map(async (item) => {
      const { categories } = await fetchPage(item.page);
      const slot = slotFromCategories(categories);
      if (!slot)
        throw new Error(`Could not determine a slot for ${item.name} from its wiki categories.`);
      return { ...item, slot };
    }),
  );
}

async function downloadImages(items: SlottedItem[]): Promise<LocalItem[]> {
  await mkdir(assetDirectory, { recursive: true });
  return Promise.all(
    items.map(async (item) => {
      const file = await downloadImage(item.name, item.imageUrl, assetDirectory);
      return { ...item, image: `images/weapons/experimental/${file}` };
    }),
  );
}

function buildCatalog(items: LocalItem[]): PartialWeaponCatalog {
  const catalog: PartialWeaponCatalog = {};
  for (const name of classes) catalog[name] = {};
  for (const item of items) {
    const slot = (catalog[item.className][item.slot] ??= []);
    slot.push({ name: item.name, image: item.image });
  }
  return catalog;
}

async function main() {
  const { document } = await fetchPage('Item_Qualities/Experimental');
  const parsed = parseItems(document);
  if (parsed.length < 15)
    throw new Error(
      `Refusing to replace experimental data: only ${parsed.length} items were scraped.`,
    );

  const items = await addSlots(parsed);
  const localized = await downloadImages(items);
  const catalog = buildCatalog(localized);
  const source = `// Generated by pnpm scrape:experimental. Do not edit manually.\n\nimport type { PartialWeaponCatalog } from './index';\n\nexport const experimentalWeapons: PartialWeaponCatalog = ${JSON.stringify(catalog, null, 2)};\n`;
  await writeFile(outputFile, source, 'utf8');

  const expectedFiles = new Set(localized.map((item) => path.basename(item.image)));
  for (const file of await readdir(assetDirectory)) {
    if (!expectedFiles.has(file)) await rm(path.join(assetDirectory, file));
  }
  console.log(
    `Generated ${localized.length} experimental weapons in ${path.relative(projectRoot, outputFile)}.`,
  );
}

await main();
